# Generated by Django 5.2 on 2025-04-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_is_read_message_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
