# Generated by Django 5.2 on 2025-04-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
